pub mod availability;
pub mod compare;
pub mod config;
pub mod differential;
pub mod dream_team;
pub mod fdr;
pub mod fdr_form;
pub mod fixture;
pub mod fixture_summary;
pub mod gameweek;
pub mod history;
pub mod history_past;
pub mod live;
pub mod manager;
pub mod mini_league;
pub mod my_leagues;
pub mod my_team;
pub mod pick;
pub mod player;
pub mod region;
pub mod set_piece;
pub mod status;
pub mod summary;
pub mod swing;
pub mod table;
pub mod talisman;
pub mod team;
pub mod team_availability;
pub mod team_form;
pub mod team_ha;
pub mod team_perf;
pub mod team_trend;
pub mod template;
pub mod top;
pub mod transfer;
pub mod transfer_history;
pub mod trend;
pub mod xa;
pub mod xg;
pub mod xgc;
pub mod xgi;

pub use availability::handle_availability;
pub use compare::handle_compare;
pub use config::{ConfigArgs, handle_config};
pub use differential::handle_differential;
pub use dream_team::handle_dream_team;
pub use fdr::handle_fixture_difficulty_rating;
pub use fdr_form::handle_fdr_form;
pub use fixture::{FixtureArgs, handle_fixture};
pub use fixture_summary::handle_fixture_summary;
pub use gameweek::handle_gameweek;
pub use history::{HistoryArgs, handle_history};
pub use history_past::handle_history_past;
pub use live::handle_live;
pub use manager::handle_manager;
pub use mini_league::{MiniLeagueArgs, handle_mini_league};
pub use my_leagues::{MyLeaguesArgs, handle_my_leagues};
pub use my_team::{MyTeamArgs, handle_my_team};
pub use pick::handle_pick;
pub use player::{PlayerFilterArgs, handle_player};
pub use region::handle_region;
pub use set_piece::handle_set_piece;
pub use status::handle_status;
pub use summary::handle_player_summary;
pub use swing::{SwingArgs, handle_swing};
pub use table::handle_table;
pub use talisman::handle_talisman;
pub use team::handle_team;
pub use team_availability::handle_team_availability;
pub use team_form::handle_team_form;
pub use team_ha::handle_team_ha;
pub use team_perf::handle_team_perf;
pub use team_trend::handle_team_trend;
pub use template::handle_template;
pub use top::handle_top;
pub use transfer::{TransferArgs, handle_transfer};
pub use transfer_history::{TransferHistoryArgs, handle_transfer_history};
pub use trend::handle_trend;
pub use xa::handle_xa;
pub use xg::handle_xg;
pub use xgc::handle_xgc;
pub use xgi::handle_xgi;
