pub mod availability;
pub mod config;
pub mod dream_team;
pub mod fdr;
pub mod fixture;
pub mod gameweek;
pub mod history;
pub mod live;
pub mod my_team;
pub mod pick;
pub mod player;
pub mod set_piece;
pub mod status;
pub mod summary;
pub mod table;
pub mod team;
pub mod team_form;
pub mod team_perf;
pub mod transfer;

pub use availability::handle_availability;
pub use config::{ConfigArgs, handle_config};
pub use dream_team::handle_dream_team;
pub use fdr::handle_fixture_difficulty_rating;
pub use fixture::handle_fixture;
pub use gameweek::handle_gameweek;
pub use history::{HistoryArgs, handle_history};
pub use live::handle_live;
pub use my_team::{MyTeamArgs, handle_my_team};
pub use pick::handle_pick;
pub use player::{PlayerFilterArgs, handle_player};
pub use set_piece::handle_set_piece;
pub use status::handle_status;
pub use summary::handle_player_summary;
pub use table::handle_table;
pub use team::handle_team;
pub use team_form::handle_team_form;
pub use team_perf::handle_team_perf;
pub use transfer::{TransferArgs, handle_transfer};
